/*
 * CTE - C Tablić Engine : Bitboard Precomputed Tables Header
 * Auto-generated by tools/bitboard_gen.py - DO NOT EDIT DIRECTLY
 * Total precomputed base subset masks: 28855
 */

#ifndef __CTE_BITBOARD_TABLES_H
#define __CTE_BITBOARD_TABLES_H

#include <stdint.h>
#include <stddef.h>

#define CTE_TOTAL_BASE_MASKS 28855
#define CTE_PIVOT_INDEX(c, v) ((uint16_t)((c) * 15 + (v)))

// Fast reachability filter: 1 bit per card if it can participate in sum V
extern const uint64_t g_reachability_mask[15];

// Linearized 1D metadata (52 cards * 15 values = 780 entries)
extern const uint16_t g_pivot_offsets[780];
extern const uint16_t g_pivot_counts[780];

// Flat contiguous 1D array of all precomputed base subset masks (64-byte aligned)
extern const uint64_t g_pivot_subset_masks[CTE_TOTAL_BASE_MASKS];

#endif /* __CTE_BITBOARD_TABLES_H */
