/*
 * CTE - C Tablić Engine : Bitboard Precomputed Tables Header
 * Auto-generated by tools/bitboard_gen.py - DO NOT EDIT DIRECTLY
 * Total precomputed base subset masks: 28855
 *
 * PoC branch: g_suit_sum (13-bit rank LUT, 8 KB) re-enabled for
 * Piste A and Piste B suit-sum carry-rippler generators.
 */

#ifndef __CTE_BITBOARD_TABLES_H
#define __CTE_BITBOARD_TABLES_H

#include <stdint.h>
#include <stddef.h>

#define CTE_TOTAL_BASE_MASKS 28855
#define CTE_PIVOT_INDEX(c, v) ((uint16_t)((c) * 15 + (v)))

// Fast reachability filter: 1 bit per card if it can participate in sum V
extern const uint64_t g_reachability_mask[15];

// Linearized 1D metadata (52 cards * 15 values = 780 entries)
extern const uint16_t g_pivot_offsets[780];
extern const uint16_t g_pivot_counts[780];

// Flat contiguous 1D array of all precomputed base subset masks (64-byte aligned)
extern const uint64_t g_pivot_subset_masks[CTE_TOTAL_BASE_MASKS];

// 13-bit rank-mask -> nominal sum LUT (8 KB, L1D resident)
// g_suit_sum[rank_mask] = sum of nominal values of cards in that rank mask
// Usage: SUIT_SUM_4(bb) splits a 52-bit card bitboard into 4 x 13-bit suit slices
extern uint8_t g_suit_sum[8192];
void init_suit_sum(void);

#define SUIT_SUM_4(bb) ( (uint8_t)(g_suit_sum[(bb) & 0x1FFF] \
                       + g_suit_sum[((bb) >> 13) & 0x1FFF] \
                       + g_suit_sum[((bb) >> 26) & 0x1FFF] \
                       + g_suit_sum[((bb) >> 39) & 0x1FFF]) )

#endif /* __CTE_BITBOARD_TABLES_H */
