#!/usr/bin/env python3
"""
CTE - Bitboard Table Generator (bitboard_gen.py)
Precomputes all elementary 64-bit card subset masks with a 1D Pivot Inverted Index
and Fast-Rejection Reachability Bitmasks.

Outputs:
  - include/bitboard_tables.h (declarations)
  - src/bitboard_tables.c    (contiguous 1D data definitions)
"""

import sys
import os

RANK_VALUES = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
RANK_NAMES = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "A", "J", "Q", "K"]
SUIT_NAMES = ["C", "D", "H", "S"]

def get_card_name(c):
    return f"{RANK_NAMES[c % 13]}{SUIT_NAMES[c // 13]}"

def is_ace(c):
    return (c % 13) == 9

def card_val_11(c):
    return RANK_VALUES[c % 13]

def subset_sums_to(subset, target):
    if not subset:
        return False
    nom_sum = sum(card_val_11(c) for c in subset)
    num_aces = sum(1 for c in subset if is_ace(c))
    if nom_sum < target:
        return False
    diff = nom_sum - target
    if diff % 10 != 0:
        return False
    k = diff // 10
    return k <= num_aces

def find_subsets_for_target(target):
    results = []
    cards = list(range(52))

    def backtrack(start_idx, current_subset, current_min_sum):
        if current_min_sum > target:
            return
        if current_subset and subset_sums_to(current_subset, target):
            mask = sum(1 << c for c in current_subset)
            results.append(mask)

        for i in range(start_idx, 52):
            c = cards[i]
            val_min = 1 if is_ace(c) else RANK_VALUES[c % 13]
            if current_min_sum + val_min > target:
                continue
            current_subset.append(c)
            backtrack(i + 1, current_subset, current_min_sum + val_min)
            current_subset.pop()

    backtrack(0, [], 0)
    return sorted(list(set(results)))

def lowest_set_bit(mask):
    return (mask & -mask).bit_length() - 1

def main():
    targets = list(range(1, 15))
    
    # reachability_masks[V] = bitwise OR of all valid masks for target V
    reachability_masks = {0: 0}
    for t in targets:
        reachability_masks[t] = 0

    # buckets[(card, val)] = list of masks where card is the lowest card
    buckets = {}
    for c in range(52):
        for v in range(15):
            buckets[(c, v)] = []

    total_masks = 0
    for t in targets:
        masks = find_subsets_for_target(t)
        total_masks += len(masks)
        for m in masks:
            reachability_masks[t] |= m
            pivot = lowest_set_bit(m)
            buckets[(pivot, t)].append(m)

    # Linearize into flat 1D arrays
    # 52 cards * 15 values = 780 entries
    NUM_ENTRIES = 52 * 15
    pivot_offsets = [0] * NUM_ENTRIES
    pivot_counts = [0] * NUM_ENTRIES
    flat_masks = []
    cur_offset = 0

    for c in range(52):
        for v in range(15):
            idx = c * 15 + v
            m_list = buckets[(c, v)]
            pivot_offsets[idx] = cur_offset
            pivot_counts[idx] = len(m_list)
            cur_offset += len(m_list)
            flat_masks.extend(m_list)

    assert len(flat_masks) == total_masks

    # 1. Write include/bitboard_tables.h
    with open("include/bitboard_tables.h", "w") as fh:
        fh.write("/*\n")
        fh.write(" * CTE - C Tablić Engine : Bitboard Precomputed Tables Header\n")
        fh.write(" * Auto-generated by tools/bitboard_gen.py - DO NOT EDIT DIRECTLY\n")
        fh.write(f" * Total precomputed base subset masks: {total_masks}\n")
        fh.write(" */\n\n")
        fh.write("#ifndef __CTE_BITBOARD_TABLES_H\n")
        fh.write("#define __CTE_BITBOARD_TABLES_H\n\n")
        fh.write("#include <stdint.h>\n")
        fh.write("#include <stddef.h>\n\n")
        fh.write(f"#define CTE_TOTAL_BASE_MASKS {total_masks}\n")
        fh.write("#define CTE_PIVOT_INDEX(c, v) ((uint16_t)((c) * 15 + (v)))\n\n")
        fh.write("// Fast reachability filter: 1 bit per card if it can participate in sum V\n")
        fh.write("extern const uint64_t g_reachability_mask[15];\n\n")
        fh.write("// Linearized 1D metadata (52 cards * 15 values = 780 entries)\n")
        fh.write("extern const uint16_t g_pivot_offsets[780];\n")
        fh.write("extern const uint16_t g_pivot_counts[780];\n\n")
        fh.write("// Flat contiguous 1D array of all precomputed base subset masks (64-byte aligned)\n")
        fh.write("extern const uint64_t g_pivot_subset_masks[CTE_TOTAL_BASE_MASKS];\n\n")
        fh.write("#endif /* __CTE_BITBOARD_TABLES_H */\n")

    # 2. Write src/bitboard_tables.c
    with open("src/bitboard_tables.c", "w") as fc:
        fc.write("/*\n")
        fc.write(" * CTE - C Tablić Engine : Bitboard Precomputed Tables Definitions\n")
        fc.write(" * Auto-generated by tools/bitboard_gen.py - DO NOT EDIT DIRECTLY\n")
        fc.write(" */\n\n")
        fc.write('#include "bitboard_tables.h"\n\n')

        # g_reachability_mask
        fc.write("const uint64_t g_reachability_mask[15] = {\n")
        fc.write("    0x0ULL, // 0 unused\n")
        for t in targets:
            name = "Ace (1)" if t == 1 else f"Target {t} ({RANK_NAMES[t-2] if t >= 2 else '1'})"
            fc.write(f"    0x{reachability_masks[t]:016x}ULL, // [{t:2d}] {name}\n")
        fc.write("};\n\n")

        # g_pivot_offsets
        fc.write("const uint16_t g_pivot_offsets[780] = {\n")
        for i in range(0, NUM_ENTRIES, 15):
            c = i // 15
            c_name = get_card_name(c)
            vals = ", ".join(f"{pivot_offsets[i+v]:5d}" for v in range(15))
            fc.write(f"    /* Card {c:2d} ({c_name:3s}) */ {vals},\n")
        fc.write("};\n\n")

        # g_pivot_counts
        fc.write("const uint16_t g_pivot_counts[780] = {\n")
        for i in range(0, NUM_ENTRIES, 15):
            c = i // 15
            c_name = get_card_name(c)
            vals = ", ".join(f"{pivot_counts[i+v]:3d}" for v in range(15))
            fc.write(f"    /* Card {c:2d} ({c_name:3s}) */ {vals},\n")
        fc.write("};\n\n")

        # g_pivot_subset_masks (1D flat array)
        fc.write("#if defined(__GNUC__) || defined(__clang__)\n")
        fc.write("const uint64_t g_pivot_subset_masks[CTE_TOTAL_BASE_MASKS] __attribute__((aligned(64))) = {\n")
        fc.write("#else\n")
        fc.write("const uint64_t g_pivot_subset_masks[CTE_TOTAL_BASE_MASKS] = {\n")
        fc.write("#endif\n")

        mask_idx = 0
        for c in range(52):
            for v in range(15):
                m_list = buckets[(c, v)]
                if not m_list:
                    continue
                c_name = get_card_name(c)
                v_name = "Ace(1)" if v == 1 else f"Val {v}"
                fc.write(f"    /* --- Pivot Card {c:2d} ({c_name}), {v_name} ({len(m_list)} masks, offset {pivot_offsets[c*15+v]}) --- */\n")
                for m in m_list:
                    cards_in_m = [ci for ci in range(52) if (m & (1 << ci))]
                    names_str = " + ".join(get_card_name(ci) for ci in cards_in_m)
                    fc.write(f"    0x{m:016x}ULL, /* [{mask_idx:5d}] {names_str} */\n")
                    mask_idx += 1
                fc.write("\n")

        fc.write("};\n")

if __name__ == "__main__":
    main()
